---
swagger: '2.0'
info:
  title: API V1
  version: v1
paths:
  "/api/authentication":
    post:
      summary: Authenticate
      consumes:
      - application/json
      produces:
      - application/json
      tags:
      - authentication
      parameters:
      - name: body
        in: body
        required: true
        schema:
          type: object
          required: true
          properties:
            user:
              type: object
              required: true
              properties:
                email:
                  type: string
                  example: test_user@user.pl
                password:
                  type: string
                  example: test_user
      responses:
        '201':
          description: Returns jwt for authenticated user
        '401':
          description: invalid credentials
  "/api/clubs":
    get:
      summary: Get clubs
      consumes:
      - application/json
      produces:
      - application/json
      tags:
      - clubs
      description: Returns all user's clubs
      parameters:
      - in: header
        name: Authorization
        required: true
        type: string
        example: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOjIsInZlciI6MSwiZXhwIjo0NzQwMjMyOTkyfQ.pFrhdrKLPY2iDUOiqBgyioFtEz3qzEYYt8dFx997vOE
      responses:
        '200':
          description: returns user's clubs
        '401':
          description: unauthorized
    post:
      summary: Create new club
      consumes:
      - application/json
      produces:
      - application/json
      description: Creates new club and grants PRESIDENT role to current user
      tags:
      - clubs
      parameters:
      - name: body
        in: body
        required: true
        schema:
          type: object
          required: true
          properties:
            club:
              type: object
              required: true
              properties:
                name:
                  type: string
                  example: Warta Poznań U19
      - in: header
        name: Authorization
        required: true
        type: string
        example: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOjIsInZlciI6MSwiZXhwIjo0NzQwMjMyOTkyfQ.pFrhdrKLPY2iDUOiqBgyioFtEz3qzEYYt8dFx997vOE
      responses:
        '201':
          description: creates new club
        '422':
          description: name can not be empty
  "/api/clubs/{id}":
    get:
      summary: Get clubs
      consumes:
      - application/json
      produces:
      - application/json
      tags:
      - clubs
      description: Returns club only if it is user's club
      parameters:
      - in: header
        name: Authorization
        required: true
        type: string
        example: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOjIsInZlciI6MSwiZXhwIjo0NzQwMjMyOTkyfQ.pFrhdrKLPY2iDUOiqBgyioFtEz3qzEYYt8dFx997vOE
      - in: path
        name: id
        required: true
        type: string
        example: '1'
      responses:
        '200':
          description: returns club
        '401':
          description: unauthorized
  "/api/clubs/{club_id}/events":
    post:
      summary: Create new event
      consumes:
      - application/json
      produces:
      - application/json
      description: Creates new event for club
      tags:
      - events
      parameters:
      - name: body
        in: body
        required: true
        schema:
          type: object
          required: true
          properties:
            event:
              type: object
              required: true
              properties:
                name:
                  type: string
                  example: Warta Poznań U19 - Lech Poznań U19
                start_date:
                  type: integer
                  example: 0
      - in: header
        name: Authorization
        required: true
        type: string
        example: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOjIsInZlciI6MSwiZXhwIjo0NzQwMjMyOTkyfQ.pFrhdrKLPY2iDUOiqBgyioFtEz3qzEYYt8dFx997vOE
      - in: path
        name: club_id
        required: true
        type: string
        example: '1'
      responses:
        '201':
          description: creates new event
        '422':
          description: name can not be empty
  "/api/users":
    post:
      summary: Sign up
      consumes:
      - application/json
      produces:
      - application/json
      tags:
      - users
      parameters:
      - name: body
        in: body
        required: true
        schema:
          type: object
          required: true
          properties:
            user:
              type: object
              required: true
              properties:
                email:
                  type: string
                  example: test_user@user.pl
                password:
                  type: string
                  example: test_user
      responses:
        '201':
          description: creates new user
        '422':
          description: email has been taken or invalid
