---
swagger: '2.0'
info:
  title: API V1
  version: v1
paths:
  "/api/authentication":
    post:
      summary: Authenticate
      consumes:
      - application/json
      produces:
      - application/json
      tags:
      - authentication
      parameters:
      - name: body
        in: body
        required: true
        schema:
          type: object
          required: true
          properties:
            user:
              type: object
              required: true
              properties:
                email:
                  type: string
                  example: test_user@user.pl
                password:
                  type: string
                  example: test_user
      responses:
        '201':
          description: Returns jwt for authenticated user
        '401':
          description: invalid credentials
  "/api/users":
    post:
      summary: Sign up
      consumes:
      - application/json
      produces:
      - application/json
      tags:
      - users
      parameters:
      - name: body
        in: body
        required: true
        schema:
          type: object
          required: true
          properties:
            user:
              type: object
              required: true
              properties:
                email:
                  type: string
                  example: test_user@user.pl
                password:
                  type: string
                  example: test_user
      responses:
        '201':
          description: creates new user
        '422':
          description: email has been taken or invalid
