---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/users":
    get:
      summary: Get users
      consumes:
      - application/json
      produces:
      - application/json
      tags:
      - users
      responses:
        '200':
          description:
            description: Return all the available users
        '401':
          description:
            description: Return all the available users
  "/api/users/{id}":
    get:
      summary: Get user
      consumes:
      - application/json
      produces:
      - application/json
      tags:
      - users
      parameters:
      - name: id
        in: path
        type: integer
        required: true
      responses:
        '200':
          description:
            description: Return all the available users
        '401':
          description:
            description: Return all the available users
