---
swagger: '2.0'
info:
  title: API V1
  version: v1
paths:
  "/api/authentication":
    post:
      summary: Authenticate
      consumes:
      - application/json
      produces:
      - application/json
      tags:
      - authentication
      parameters:
      - name: body
        in: body
        required: true
        schema:
          type: object
          required: true
          properties:
            user:
              type: object
              required: true
              properties:
                email:
                  type: string
                  example: test_user@user.pl
                password:
                  type: string
                  example: test_user
      responses:
        '201':
          description: 'Returns jwt for '
        '401':
          description: invalid credentials
  "/api/users":
    get:
      summary: Get users
      consumes:
      - application/json
      produces:
      - application/json
      tags:
      - users
      parameters:
      - name: Authorization
        in: header
        type: string
      responses:
        '200':
          description: Return all the available users
        '401':
          description: Return all the available users
  "/api/users/{id}":
    get:
      summary: Get user
      consumes:
      - application/json
      produces:
      - application/json
      tags:
      - users
      parameters:
      - name: Authorization
        in: header
        type: string
      - name: id
        in: path
        type: integer
        required: true
      responses:
        '200':
          description: Return all the available users
        '401':
          description: Return all the available users
